# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Validate-YAML

on:
  push:
    branches: [main, v7.1, next-patch]
  pull_request:
    branches: [main, v7.1, next-patch]

permissions:
  contents: read

jobs:
  validate-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GEDCOM.io
        uses: actions/checkout@v4

      - name: Validate YAML
        run: yamllint .yamllint.yml .github .github/workflows
